python format_door_list_A.py
python test_margin_A.py
del "..\door_formatted_A.xlsx"
python format_door_list_B.py
python test_margin_B.py
del "..\door_formatted_B.xlsx"
python format_door_list_C.py
python test_margin_C.py
del "..\door_formatted_C.xlsx"